insert into "parking_spot" ("id") values (1)
insert into "parking_spot" ("id") values (2)
insert into "parking_spot" ("id") values (3)
insert into "parking_spot" ("id") values (4)
insert into "parking_spot" ("id") values (5)
insert into "app_details" ("type", "details") values ('api_key', '61bed41a6bb495305b1b21efbbd80c4d')
